# .github/workflows/update_articles.yml

name: Update Healthcare AI Articles Weekly

on:
  schedule:
    - cron: "0 8 * * 0"  # Every Sunday at 8am UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update articles.json from RSS
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run article updater
        run: |
          pip install feedparser
          python scripts/update_articles.py

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/articles.json
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Weekly article refresh"
          git push
